Testing Azure-DevOps OIDC 1

diff --git a/azure-oidc.yaml b/azure-oidc.yaml
--- a/azure-oidc.yaml
+++ b/azure-oidc.yaml
@@ -6,34 +6,61 @@ pool:
 
 variables:
   AWS_REGION: 'ap-south-1'
-  AWS_ROLE_ARN: 'arn:aws:iam::306005333932:role/week-4-azure-devop'
+  AWS_ROLE_ARN: 'arn:aws:iam::306005333932:role/terraform-azdo-oidc-role'
+  serviceConnectionName: 'aws-oidc-federation'
 
 steps:
-- task: AzureCLI@2
-  displayName: 'Get OIDC token and assume AWS role'
-  inputs:
-    azureSubscription: 'aws-oidc-federation'   # the dummy service connection
-    scriptType: bash
-    scriptLocation: inlineScript
-    inlineScript: |
-      set -e
+- bash: |
+    set -e
 
-      # Get the OIDC token Azure DevOps issued for this service connection
-      ID_TOKEN=$(curl -s -X POST \
-        "https://vstoken.dev.azure.com/$(System.CollectionId)/oidctoken?api-version=7.1&serviceConnectionId=$(az devops service-endpoint list --query "[?name=='aws-oidc-federation'].id" -o tsv)" \
-        -H "Authorization: Bearer $(System.AccessToken)" \
-        -H "Content-Type: application/json" | jq -r '.oidcToken')
+    ORG_URL="$(System.CollectionUri)"
+    PROJECT_ID="$(System.TeamProjectId)"
+    PLAN_ID="$(System.PlanId)"
+    JOB_ID="$(System.JobId)"
+    HUB="$(System.HostType)"
 
-      # Exchange it for temporary AWS credentials
-      CREDS=$(aws sts assume-role-with-web-identity \
-        --role-arn "$(AWS_ROLE_ARN)" \
-        --role-session-name "azdo-pipeline-$(Build.BuildId)" \
-        --web-identity-token "$ID_TOKEN" \
-        --duration-seconds 3600)
+    # Look up the service connection ID by name
+    SC_ID=$(curl -s -u ":$(System.AccessToken)" \
+      "$ORG_URL$PROJECT_ID/_apis/serviceendpoint/endpoints?endpointNames=$(serviceConnectionName)&api-version=7.1" \
+      | jq -r '.value[0].id')
 
-      echo "##vso[task.setvariable variable=AWS_ACCESS_KEY_ID;issecret=true]$(echo $CREDS | jq -r '.Credentials.AccessKeyId')"
-      echo "##vso[task.setvariable variable=AWS_SECRET_ACCESS_KEY;issecret=true]$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')"
-      echo "##vso[task.setvariable variable=AWS_SESSION_TOKEN;issecret=true]$(echo $CREDS | jq -r '.Credentials.SessionToken')"
+    if [ -z "$SC_ID" ] || [ "$SC_ID" == "null" ]; then
+      echo "##vso[task.logissue type=error]Could not resolve service connection ID for $(serviceConnectionName)"
+      exit 1
+    fi
+
+    echo "Resolved service connection ID: $SC_ID"
+
+    # Request the OIDC token tied to this job/plan/service connection
+    OIDC_RESPONSE=$(curl -s -X POST \
+      -u ":$(System.AccessToken)" \
+      -H "Content-Type: application/json" \
+      "$ORG_URL$PROJECT_ID/_apis/distributedtask/hubs/$HUB/plans/$PLAN_ID/jobs/$JOB_ID/oidctoken?serviceConnectionId=$SC_ID&api-version=7.1-preview.1")
+
+    ID_TOKEN=$(echo "$OIDC_RESPONSE" | jq -r '.oidcToken')
+
+    if [ -z "$ID_TOKEN" ] || [ "$ID_TOKEN" == "null" ]; then
+      echo "##vso[task.logissue type=error]Failed to retrieve OIDC token. Response: $OIDC_RESPONSE"
+      exit 1
+    fi
+
+    echo "##vso[task.setvariable variable=OIDC_TOKEN;issecret=true]$ID_TOKEN"
+  displayName: 'Get Azure DevOps OIDC token'
+  env:
+    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+
+- bash: |
+    set -e
+    CREDS=$(aws sts assume-role-with-web-identity \
+      --role-arn "$(AWS_ROLE_ARN)" \
+      --role-session-name "azdo-pipeline-$(Build.BuildId)" \
+      --web-identity-token "$(OIDC_TOKEN)" \
+      --duration-seconds 3600)
+
+    echo "##vso[task.setvariable variable=AWS_ACCESS_KEY_ID;issecret=true]$(echo $CREDS | jq -r '.Credentials.AccessKeyId')"
+    echo "##vso[task.setvariable variable=AWS_SECRET_ACCESS_KEY;issecret=true]$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')"
+    echo "##vso[task.setvariable variable=AWS_SESSION_TOKEN;issecret=true]$(echo $CREDS | jq -r '.Credentials.SessionToken')"
+  displayName: 'Assume AWS role via web identity'
 
 - script: |
     terraform init
